-- Spinner Templates Table
CREATE TABLE IF NOT EXISTS spinner_templates (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    content TEXT NOT NULL,
    subject TEXT,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert some default templates
INSERT OR IGNORE INTO spinner_templates (name, content, subject, description) VALUES
('Introduction Email', '{Hello|Hi|Greetings} {{first_name}},\n\nI {hope|trust} this email finds you well. My name is {{sender_name}} from {our company|our organization|our team}, and I {wanted to|would like to} {introduce myself|connect with you|reach out}.\n\n{I came across your profile|I found your contact|I was referred to you} {and thought|and believed|and felt} {we might|we could|there''s potential to} {collaborate|work together|benefit from connecting}.\n\n{Would you be interested in|Are you available for|Do you have time for} a {quick|brief|short} {call|chat|meeting} to {discuss|talk about|explore} {potential opportunities|how we might work together|possible synergies}?\n\n{Thanks|Thank you|Regards},\n{{sender_name}}\n{{sender_email}}', '{Hello|Hi|Greetings} from {{sender_name}} - {Let''s connect|Introduction|Nice to meet you}', 'A professional introduction email template'),

('Follow-up Email', '{Hello|Hi|Greetings} {{first_name}},\n\nI {wanted to|am writing to|thought I''d} {follow up|check in|touch base} {regarding|about|concerning} our {recent|previous|last} {conversation|discussion|meeting}.\n\n{I was wondering|I wanted to know|I''m curious} if you''ve had a chance to {consider|think about|review} {what we discussed|our conversation|the information I shared}.\n\n{Let me know|Please share|I''d appreciate} your {thoughts|feedback|opinion} when you have a moment.\n\n{Thanks|Thank you|Best regards},\n{{sender_name}}\n{{sender_email}}', '{Following up|Just checking in|Quick follow-up} on our {conversation|discussion|meeting}', 'A follow-up email template'),

('Newsletter', '<div style=\"font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;\">\n    <div style=\"background-color: #f8f9fa; padding: 20px; text-align: center;\">\n        <h1 style=\"color: #333;\">{Monthly|Weekly|Quarterly} Newsletter</h1>\n        <p style=\"color: #666;\">{{current_date}}</p>\n    </div>\n    \n    <div style=\"padding: 20px;\">\n        <h2 style=\"color: #333;\">{Hello|Greetings|Hi} {{first_name}},</h2>\n        \n        <p>{We hope|We trust|We''re confident} this newsletter finds you well. Here are our {latest|recent|new} updates:</p>\n        \n        <h3 style=\"color: #333;\">{Exciting|Important|Key} {Announcement|News|Update}</h3>\n        <p>{We''re thrilled|We''re excited|We''re pleased} to {announce|share|inform you about} our {latest|newest|most recent} {product|service|offering}.</p>\n        \n        <h3 style=\"color: #333;\">{Upcoming|Future|Scheduled} {Events|Webinars|Meetings}</h3>\n        <p>Join us for our {upcoming|next|scheduled} {event|webinar|workshop} on {various topics|industry trends|best practices}.</p>\n        \n        <h3 style=\"color: #333;\">{Helpful|Useful|Valuable} {Resources|Tips|Information}</h3>\n        <p>Check out our {blog|resource center|knowledge base} for {helpful|useful|valuable} {tips|information|resources}.</p>\n        \n        <p>{Thank you|We appreciate|We value} your {continued|ongoing|loyal} {support|partnership|business}.</p>\n        \n        <p>{Best regards|Sincerely|Thanks},<br>\n        {{sender_name}}<br>\n        {{sender_email}}</p>\n    </div>\n    \n    <div style=\"background-color: #f8f9fa; padding: 10px; text-align: center; font-size: 12px; color: #666;\">\n        <p>To unsubscribe, {click here|follow this link|reply with ''unsubscribe''}.</p>\n    </div>\n</div>', '{Latest|New|Recent} {Updates|News|Developments} from {Our Team|Our Company|Us}', 'A newsletter email template with HTML formatting');