services:
  - type: web
    name: senderblade
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/app_sender.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PORT
        value: 5001
    plan: free